version: '3'

services:
  springboot-deploy:
    image: springboot-deploy
    ports:
      - "8081:8081"
    networks:
      - employee-mysql
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:8
    networks:
      - employee-mysql
    environment:
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=tieptv
      - MYSQL_USERNAME=root

networks:
  employee-mysql:

