version: '3'

services:
  app:
    container_name: springboot-deploy
    ports:
      - "8081:8081"
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - employee-mysql
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:8
    container_name: mysqldb
    restart: always
    networks:
      - employee-mysql
    environment:
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=bootdb

networks:
  employee-mysql:

